blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.com/invite/resourcefulbees
    about: If you have any questions about anything ask on out Discord. Otherwise click one of the templates above.
