["Coal Config"]

["Coal Config".Overworld]
generate_in_the_overworld = true

["Coal Config"."The Nether"]
generate_in_the_nether = true

["Iron Config"]

["Iron Config".Overworld]
generate_in_the_overworld = true

["Iron Config"."The Nether"]
generate_in_the_nether = true

["Gold Config"]

["Gold Config".Overworld]
generate_in_the_overworld = true

["Gold Config"."The Nether"]
generate_in_the_nether = true

["Nether Quartz Config"]

["Nether Quartz Config".Overworld]
generate_in_the_overworld = false

["Nether Quartz Config"."The Nether"]
generate_in_the_nether = true

["Cobalt Config"]

["Cobalt Config".Overworld]
generate_in_the_overworld = false

["Iridium Config"]

["Iridium Config".Overworld]
generate_in_the_overworld = false

["Certus Quartz Config"]

["Certus Quartz Config".Overworld]
generate_in_the_overworld = false

["Charged Certus Quartz Config"]

["Charged Certus Quartz Config".Overworld]
generate_in_the_overworld = false

["Bitumen Config"]

["Bitumen Config"."The Nether"]
generate_in_the_nether = true

["Sulfur Config"]

["Sulfur Config"."The Nether"]
generate_in_the_nether = true

["Dimensional Shard Config"]

["Dimensional Shard Config"."The Nether"]
generate_in_the_nether = true

["Dimensional Shard Config"."The End"]
generate_in_the_end = true

["Ruby Config"]

["Ruby Config".Overworld]
overworld_base = 5
overworld_count = 2
overworld_size = 3

["Sapphire Config"]

["Sapphire Config".Overworld]
overworld_base = 5
overworld_count = 2
overworld_size = 3

["Peridot Config"]

["Peridot Config".Overworld]
overworld_base = 5
overworld_count = 2
overworld_size = 3

["Stratum Config: minecraft_stone"]
active = true

["Stratum Config: minecraft_andesite"]
active = true

["Stratum Config: minecraft_granite"]
active = true

["Stratum Config: minecraft_diorite"]
active = true

["Stratum Config: minecraft_sand"]
active = true

["Stratum Config: minecraft_gravel"]
active = true

["Stratum Config: minecraft_netherrack"]
active = true

["Stratum Config: minecraft_blackstone"]
active = true

["Stratum Config: minecraft_basalt"]
active = true

["Stratum Config: minecraft_soul_soil"]
active = true

["Stratum Config: minecraft_end_stone"]
active = true

["Stratum Config: create_gabbro"]
active = true

["Stratum Config: create_limestone"]
active = true

["Stratum Config: create_scoria"]
active = true

["Stratum Config: create_weathered_limestone"]
active = true

["Stratum Config: quark_jasper"]
active = true

["Stratum Config: quark_marble"]
active = true

["Stratum Config: quark_slate"]
active = true

["Stratum Config: quark_deepslate"]
active = true

["Stratum Config: byg_mossy_stone"]
active = true

["Stratum Config: byg_brimstone"]
active = true

["Stratum Config: byg_subzero_ash"]
active = true

["Stratum Config: byg_blue_netherrack"]
active = true

["Stratum Config: byg_nylium_soul_soil"]
active = true

["Stratum Config: byg_ether_stone"]
active = true

["Stratum Config: byg_cryptic_stone"]
active = true

["Stratum Config: betterend_flavolite"]
active = true

["Stratum Config: betterend_sulphuric_rock"]
active = true

["Stratum Config: betterend_violecite"]
active = true

["Stratum Config: astral_marble"]
active = true
